### ISSUE TITLE
Getting an error saying Plugin is missing for iOS: space.wisnuwiry/root_detector

### ISSUE THREAD

**Issue by randikachan** [wisnuwiry/root_detector#1]
Hi there,

I tried you plugin and for Android it's working fine. But for iOS I'm getting an error. And the exception says as following:

MissingPluginException(No implementation found for method checkIsRooted on channel space.wisnuwiry/root_detector)

Any guess what could be the issue here?

Thanks in advanced!

**Comment by wisnuwiry** [comment]
Fixed issue in root_detector version: ^0.0.6, Please use that version.

Thank you for telling me.
